"""add order history index

Revision ID: 8f495f07fa4f
Revises: 2da80f6ed769
Create Date: 2026-08-11 23:38:44.197261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f495f07fa4f'
down_revision: Union[str, None] = '2da80f6ed769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_orders_user_created_at', 'orders', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_user_created_at', table_name='orders')
    # ### end Alembic commands ###
