"""add product image key

Revision ID: b338bb00941a
Revises: 8f495f07fa4f
Create Date: 2026-08-13 14:45:01.592744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b338bb00941a'
down_revision: Union[str, None] = '8f495f07fa4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_key')
    # ### end Alembic commands ###
